### ISSUE TITLE
Create self-contained OS/chipset specific CLI versions

### ISSUE THREAD

**Issue by frankkilcommins** [SmartBear-DevRel/explore-cli#24]
As well as having Explore.CLI available as a nuget package, let's also ensure that we have variants available that do not require a dotnet runtime to be installed.

Beware of:
- https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/runtimespecific-app-default
- https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/arch-option

Identify publish location and update ReadMe and product docs to point to install options for the CLI

**Comment by YOU54F** [comment]
`dotnet publish -o build/osx-arm64 --arch arm64 --os osx --configuration Release -p:PublishSingleFile=true -p:SelfContained=true -p:PublishReadyToRun=true && ./build/osx-arm64/Explore.Cli`

change `--arch` and `--os` to the appropriate runtime identifier you want to target. and update `build/osx-arm64`
to your specified combo (makes it easier if you are cross compiling to output to a separate folder)

You can also add the following into the cs file


```cs
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishReadyToRun>true</PublishReadyToRun>
```

but not sure if that interferes with the publish step (still nice to have it as a nuget pkg for people to install)
