### ISSUE TITLE
Issue importing postman collections 

### ISSUE THREAD

**Issue by Nogradi123** [SmartBear-DevRel/explore-cli#33]
Currently getting this error when attempting to import any collection that has a description for any endpoint parameters. 

`An error occurred: The JSON value could not be converted to Explore.Cli.Models.Postman.Description. Path: $.item[0].item[0].request.description | LineNumber: 41 | BytePositionInLine: 69.`

Here is the attached file for a sample postman collection where the error is occuring :
[API_ documentation_postman_collection.json](https://github.com/user-attachments/files/16165497/API_.documentation_postman_collection.json)

**Comment by YOU54F** [comment]
👋🏾 

Hey @Nogradi123,

Thanks for raising and providing a Postman collection that triggers the issue. 

I have been able to replicate and fix and will raise a PR shortly

**Comment by frankkilcommins** [comment]
Fixed in v0.6.1
Nuget: https://www.nuget.org/packages/Explore.Cli
GitHub: https://github.com/SmartBear-DevRel/explore-cli/releases/tag/0.6.1

Thanks @YOU54F
