### ISSUE TITLE
Export-Spaces - Add ability to specify path/filename for export

### ISSUE THREAD

**Issue by frankkilcommins** [SmartBear-DevRel/explore-cli#6]
Currently, the `export-spaces` command will export spaces to the current directory used to issue the command to the CLI. The filename also defaults to `ExploreSpaces.json`.

Add the ability to specify the export directory and filename.

**Comment by Yousef-Majidi** [comment]
Hi @frankkilcommins 
I'd like to try to implement this.

**Comment by frankkilcommins** [comment]
Hey @Yousef-Majidi - awesome!
